[2023-02-28T01:03:38.697+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: save_date_in_file_txt.make_directory manual__2023-02-28T01:03:32.293469+00:00 [queued]>
[2023-02-28T01:03:38.718+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: save_date_in_file_txt.make_directory manual__2023-02-28T01:03:32.293469+00:00 [queued]>
[2023-02-28T01:03:38.718+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-28T01:03:38.718+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-28T01:03:38.718+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-28T01:03:38.767+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): make_directory> on 2023-02-28 01:03:32.293469+00:00
[2023-02-28T01:03:38.778+0000] {standard_task_runner.py:55} INFO - Started process 702 to run task
[2023-02-28T01:03:38.790+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'save_date_in_file_txt', 'make_directory', 'manual__2023-02-28T01:03:32.293469+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/print_date_file.py', '--cfg-path', '/tmp/tmpavq_u8uf']
[2023-02-28T01:03:38.791+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask make_directory
[2023-02-28T01:03:38.953+0000] {task_command.py:388} INFO - Running <TaskInstance: save_date_in_file_txt.make_directory manual__2023-02-28T01:03:32.293469+00:00 [running]> on host aca83939d072
[2023-02-28T01:03:39.277+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=save_date_in_file_txt
AIRFLOW_CTX_TASK_ID=make_directory
AIRFLOW_CTX_EXECUTION_DATE=2023-02-28T01:03:32.293469+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-28T01:03:32.293469+00:00
[2023-02-28T01:03:39.280+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-28T01:03:39.281+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'mkdir -p /home/pedrodesa/Área de Trabalho']
[2023-02-28T01:03:39.403+0000] {subprocess.py:86} INFO - Output:
[2023-02-28T01:03:39.426+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/home/pedrodesa’: Permission denied
[2023-02-28T01:03:39.429+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-02-28T01:03:39.462+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-02-28T01:03:39.471+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=save_date_in_file_txt, task_id=make_directory, execution_date=20230228T010332, start_date=20230228T010338, end_date=20230228T010339
[2023-02-28T01:03:39.535+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 8 for task make_directory (Bash command failed. The command returned a non-zero exit code 1.; 702)
[2023-02-28T01:03:39.585+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-28T01:03:39.786+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
