[2023-03-02T20:36:41.686+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T20:36:37.395082+00:00 [queued]>
[2023-03-02T20:36:41.704+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T20:36:37.395082+00:00 [queued]>
[2023-03-02T20:36:41.704+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T20:36:41.705+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-02T20:36:41.705+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T20:36:41.737+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): main> on 2023-03-02 20:36:37.395082+00:00
[2023-03-02T20:36:41.749+0000] {standard_task_runner.py:55} INFO - Started process 452 to run task
[2023-03-02T20:36:41.754+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'convert_csv_in_excel', 'main', 'manual__2023-03-02T20:36:37.395082+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/convert_csv_in_excel.py', '--cfg-path', '/tmp/tmp6pwp1g2h']
[2023-03-02T20:36:41.755+0000] {standard_task_runner.py:83} INFO - Job 102: Subtask main
[2023-03-02T20:36:41.935+0000] {task_command.py:388} INFO - Running <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T20:36:37.395082+00:00 [running]> on host d28bc369eb67
[2023-03-02T20:36:42.075+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=convert_csv_in_excel
AIRFLOW_CTX_TASK_ID=main
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T20:36:37.395082+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-02T20:36:37.395082+00:00
[2023-03-02T20:36:42.827+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192: DtypeWarning: Columns (7,8,11,13,31,43,44) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2023-03-02T20:36:42.892+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/convert_csv_in_excel.py", line 13, in transfrom
    data_csv.to_excel('/opt/airflow/data/operations.xlsx')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2291, in to_excel
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/excel.py", line 835, in write
    writer, engine=engine, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_openpyxl.py", line 48, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2023-03-02T20:36:42.908+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=convert_csv_in_excel, task_id=main, execution_date=20230302T203637, start_date=20230302T203641, end_date=20230302T203642
[2023-03-02T20:36:42.924+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 102 for task main (No module named 'openpyxl'; 452)
[2023-03-02T20:36:42.975+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-02T20:36:43.007+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
