[2023-03-02T20:23:23.558+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main scheduled__2023-03-02T18:30:00+00:00 [queued]>
[2023-03-02T20:23:23.577+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main scheduled__2023-03-02T18:30:00+00:00 [queued]>
[2023-03-02T20:23:23.577+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T20:23:23.578+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-02T20:23:23.579+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T20:23:23.608+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): main> on 2023-03-02 18:30:00+00:00
[2023-03-02T20:23:23.620+0000] {standard_task_runner.py:55} INFO - Started process 1349 to run task
[2023-03-02T20:23:23.624+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'convert_csv_in_excel', 'main', 'scheduled__2023-03-02T18:30:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/convert_csv_in_excel.py', '--cfg-path', '/tmp/tmp15ddfimz']
[2023-03-02T20:23:23.625+0000] {standard_task_runner.py:83} INFO - Job 63: Subtask main
[2023-03-02T20:23:23.728+0000] {task_command.py:388} INFO - Running <TaskInstance: convert_csv_in_excel.main scheduled__2023-03-02T18:30:00+00:00 [running]> on host d28bc369eb67
[2023-03-02T20:23:23.869+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=convert_csv_in_excel
AIRFLOW_CTX_TASK_ID=main
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T18:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T18:30:00+00:00
[2023-03-02T20:23:25.253+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192: DtypeWarning: Columns (7,8,11,13,31,43,44) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2023-03-02T20:23:25.337+0000] {python.py:177} INFO - Done. Returned value was:         Mission ID Mission Date  ... Bomb Damage Assessment Source ID
0                1    8/15/1943  ...                    NaN       NaN
1                2    8/15/1943  ...                    NaN    9366.0
2                3    8/15/1943  ...                    NaN       NaN
3                4    8/15/1943  ...                    NaN       NaN
4                5    8/15/1943  ...                    NaN   22585.0
...            ...          ...  ...                    ...       ...
178276      178738    2/16/1945  ...                    NaN   35815.0
178277      178739    2/16/1945  ...                    NaN   35020.0
178278      178740    2/16/1945  ...                    NaN   35022.0
178279      178741    2/16/1945  ...                    NaN       NaN
178280      178742    2/16/1945  ...                    NaN   33784.0

[178281 rows x 46 columns]
[2023-03-02T20:23:25.461+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-03-02T20:23:25.462+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-03-02T20:23:25.476+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=convert_csv_in_excel, task_id=main, execution_date=20230302T183000, start_date=20230302T202323, end_date=20230302T202325
[2023-03-02T20:23:25.492+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 63 for task main (Object of type DataFrame is not JSON serializable; 1349)
[2023-03-02T20:23:25.525+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-02T20:23:25.560+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-02T20:24:48.362+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main scheduled__2023-03-02T18:30:00+00:00 [queued]>
[2023-03-02T20:24:48.398+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main scheduled__2023-03-02T18:30:00+00:00 [queued]>
[2023-03-02T20:24:48.398+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T20:24:48.399+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-02T20:24:48.399+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T20:24:48.432+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): main> on 2023-03-02 18:30:00+00:00
[2023-03-02T20:24:48.443+0000] {standard_task_runner.py:55} INFO - Started process 1439 to run task
[2023-03-02T20:24:48.450+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'convert_csv_in_excel', 'main', 'scheduled__2023-03-02T18:30:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/convert_csv_in_excel.py', '--cfg-path', '/tmp/tmpiohcz6wh']
[2023-03-02T20:24:48.451+0000] {standard_task_runner.py:83} INFO - Job 67: Subtask main
[2023-03-02T20:24:48.540+0000] {task_command.py:388} INFO - Running <TaskInstance: convert_csv_in_excel.main scheduled__2023-03-02T18:30:00+00:00 [running]> on host d28bc369eb67
[2023-03-02T20:24:48.641+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=convert_csv_in_excel
AIRFLOW_CTX_TASK_ID=main
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T18:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T18:30:00+00:00
[2023-03-02T20:24:49.627+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192: DtypeWarning: Columns (7,8,11,13,31,43,44) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2023-03-02T20:24:49.705+0000] {python.py:177} INFO - Done. Returned value was:         Mission ID Mission Date  ... Bomb Damage Assessment Source ID
0                1    8/15/1943  ...                    NaN       NaN
1                2    8/15/1943  ...                    NaN    9366.0
2                3    8/15/1943  ...                    NaN       NaN
3                4    8/15/1943  ...                    NaN       NaN
4                5    8/15/1943  ...                    NaN   22585.0
...            ...          ...  ...                    ...       ...
178276      178738    2/16/1945  ...                    NaN   35815.0
178277      178739    2/16/1945  ...                    NaN   35020.0
178278      178740    2/16/1945  ...                    NaN   35022.0
178279      178741    2/16/1945  ...                    NaN       NaN
178280      178742    2/16/1945  ...                    NaN   33784.0

[178281 rows x 46 columns]
[2023-03-02T20:24:49.895+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-03-02T20:24:49.902+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-03-02T20:24:49.925+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=convert_csv_in_excel, task_id=main, execution_date=20230302T183000, start_date=20230302T202448, end_date=20230302T202449
[2023-03-02T20:24:49.954+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 67 for task main (Object of type DataFrame is not JSON serializable; 1439)
[2023-03-02T20:24:50.035+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-02T20:24:50.124+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
