[2023-03-02T20:57:52.514+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T20:57:48.037293+00:00 [queued]>
[2023-03-02T20:57:52.529+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T20:57:48.037293+00:00 [queued]>
[2023-03-02T20:57:52.529+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T20:57:52.529+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-02T20:57:52.529+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T20:57:52.546+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): main> on 2023-03-02 20:57:48.037293+00:00
[2023-03-02T20:57:52.553+0000] {standard_task_runner.py:55} INFO - Started process 1611 to run task
[2023-03-02T20:57:52.558+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'convert_csv_in_excel', 'main', 'manual__2023-03-02T20:57:48.037293+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/convert_csv_in_excel.py', '--cfg-path', '/tmp/tmp2d847djh']
[2023-03-02T20:57:52.558+0000] {standard_task_runner.py:83} INFO - Job 104: Subtask main
[2023-03-02T20:57:52.649+0000] {task_command.py:388} INFO - Running <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T20:57:48.037293+00:00 [running]> on host d28bc369eb67
[2023-03-02T20:57:52.739+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=convert_csv_in_excel
AIRFLOW_CTX_TASK_ID=main
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T20:57:48.037293+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-02T20:57:48.037293+00:00
[2023-03-02T20:57:53.450+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192: DtypeWarning: Columns (7,8,11,13,31,43,44) have mixed types.Specify dtype option on import or set low_memory=False.
  return self.python_callable(*self.op_args, **self.op_kwargs)

[2023-03-02T20:57:53.510+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/convert_csv_in_excel.py", line 17, in transfrom
    data.to_excel('/opt/airflow/data/operations.xlsx')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2291, in to_excel
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/excel.py", line 835, in write
    writer, engine=engine, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_openpyxl.py", line 48, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2023-03-02T20:57:53.522+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=convert_csv_in_excel, task_id=main, execution_date=20230302T205748, start_date=20230302T205752, end_date=20230302T205753
[2023-03-02T20:57:53.537+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 104 for task main (No module named 'openpyxl'; 1611)
[2023-03-02T20:57:53.575+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-02T20:57:53.607+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
