[2023-03-01T00:47:09.295+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: save_date_in_file_txt.save_date manual__2023-03-01T00:46:55.324761+00:00 [queued]>
[2023-03-01T00:47:09.310+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: save_date_in_file_txt.save_date manual__2023-03-01T00:46:55.324761+00:00 [queued]>
[2023-03-01T00:47:09.311+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-01T00:47:09.311+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-01T00:47:09.311+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-01T00:47:09.330+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): save_date> on 2023-03-01 00:46:55.324761+00:00
[2023-03-01T00:47:09.338+0000] {standard_task_runner.py:55} INFO - Started process 242 to run task
[2023-03-01T00:47:09.342+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'save_date_in_file_txt', 'save_date', 'manual__2023-03-01T00:46:55.324761+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/print_date_file.py', '--cfg-path', '/tmp/tmpd5obj2xr']
[2023-03-01T00:47:09.342+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask save_date
[2023-03-01T00:47:09.430+0000] {task_command.py:388} INFO - Running <TaskInstance: save_date_in_file_txt.save_date manual__2023-03-01T00:46:55.324761+00:00 [running]> on host 60fce3bd3be2
[2023-03-01T00:47:09.527+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=save_date_in_file_txt
AIRFLOW_CTX_TASK_ID=save_date
AIRFLOW_CTX_EXECUTION_DATE=2023-03-01T00:46:55.324761+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-01T00:46:55.324761+00:00
[2023-03-01T00:47:09.528+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-01T00:47:09.529+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'date > /opt/***/dags/dataResult']
[2023-03-01T00:47:09.545+0000] {subprocess.py:86} INFO - Output:
[2023-03-01T00:47:09.548+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /opt/***/dags/dataResult: Is a directory
[2023-03-01T00:47:09.549+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-03-01T00:47:09.565+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-01T00:47:09.571+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=save_date_in_file_txt, task_id=save_date, execution_date=20230301T004655, start_date=20230301T004709, end_date=20230301T004709
[2023-03-01T00:47:09.591+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 46 for task save_date (Bash command failed. The command returned a non-zero exit code 1.; 242)
[2023-03-01T00:47:09.636+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-01T00:47:09.664+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
