[2023-03-02T19:40:08.645+0000] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:40:08.651+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:40:08.652+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:40:08.652+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:40:08.656+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:40:08.654+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 23
    'start_date': datetime(2023, 03, 02)
                                  ^
SyntaxError: invalid token
[2023-03-02T19:40:08.663+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:40:08.730+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 0.090 seconds
[2023-03-02T19:40:38.982+0000] {processor.py:153} INFO - Started process (PID=110) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:40:38.993+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:40:38.995+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:40:38.995+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:40:38.999+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:40:38.997+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 23
    'start_date': datetime(2023, 03, 02)
                                  ^
SyntaxError: invalid token
[2023-03-02T19:40:38.999+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:40:39.030+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 0.056 seconds
[2023-03-02T19:41:09.536+0000] {processor.py:153} INFO - Started process (PID=175) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:41:09.546+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:41:09.547+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:41:09.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:41:09.551+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:41:09.550+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 23
    'start_date': datetime(2023, 03, 02)
                                  ^
SyntaxError: invalid token
[2023-03-02T19:41:09.552+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:41:09.581+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 0.051 seconds
[2023-03-02T19:41:40.187+0000] {processor.py:153} INFO - Started process (PID=239) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:41:40.191+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:41:40.193+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:41:40.192+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:41:40.198+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:41:40.196+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 23
    'start_date': datetime(2023, 03, 02)
                                  ^
SyntaxError: invalid token
[2023-03-02T19:41:40.199+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:41:40.235+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 0.054 seconds
[2023-03-02T19:42:10.538+0000] {processor.py:153} INFO - Started process (PID=304) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:42:10.561+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:42:10.562+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:42:10.562+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:42:10.564+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:42:10.564+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 23
    'start_date': datetime(2023, 03, 02)
                                  ^
SyntaxError: invalid token
[2023-03-02T19:42:10.565+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:42:10.596+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 0.063 seconds
[2023-03-02T19:42:40.650+0000] {processor.py:153} INFO - Started process (PID=368) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:42:40.663+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:42:40.664+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:42:40.664+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:42:40.672+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:42:40.666+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 23
    'start_date': datetime(2023, 03, 02)
                                  ^
SyntaxError: invalid token
[2023-03-02T19:42:40.673+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:42:40.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 0.118 seconds
[2023-03-02T19:43:08.862+0000] {processor.py:153} INFO - Started process (PID=432) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:43:08.883+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:43:08.884+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:43:08.884+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:43:10.332+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:43:10.329+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 32, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 443, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'Convert CSV to XLSX' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-03-02T19:43:10.332+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:43:10.351+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 1.495 seconds
[2023-03-02T19:43:40.934+0000] {processor.py:153} INFO - Started process (PID=497) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:43:40.947+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:43:40.948+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:43:40.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:43:41.385+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:43:41.381+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 32, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 443, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'Convert CSV to XLSX' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-03-02T19:43:41.385+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:43:41.412+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 0.483 seconds
[2023-03-02T19:44:12.425+0000] {processor.py:153} INFO - Started process (PID=563) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:44:12.433+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:44:12.434+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:44:12.434+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:44:13.187+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:44:13.182+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 32, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 443, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'Convert CSV to XLSX' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-03-02T19:44:13.187+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:44:13.253+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 0.833 seconds
[2023-03-02T19:46:41.734+0000] {processor.py:153} INFO - Started process (PID=57) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:46:41.760+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:46:41.762+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:46:41.762+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:46:45.623+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:46:45.619+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 32, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 443, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'Convert CSV to XLSX' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-03-02T19:46:45.624+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:46:45.710+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 4.007 seconds
[2023-03-02T19:47:15.892+0000] {processor.py:153} INFO - Started process (PID=127) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:47:15.894+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:47:15.895+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:47:15.895+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:47:16.393+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:47:16.389+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 32, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 443, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'Convert CSV to XLSX' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-03-02T19:47:16.393+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:47:16.420+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 0.541 seconds
[2023-03-02T19:47:46.513+0000] {processor.py:153} INFO - Started process (PID=192) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:47:46.515+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:47:46.516+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:47:46.515+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:47:46.869+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:47:46.865+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 32, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 443, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'Convert CSV to XLSX' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-03-02T19:47:46.869+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:47:46.900+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 0.391 seconds
[2023-03-02T19:48:16.946+0000] {processor.py:153} INFO - Started process (PID=257) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:48:16.953+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:48:16.955+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:48:16.954+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:48:17.509+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:48:17.504+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 32, in <module>
    catchup=False
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 443, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'Convert CSV to XLSX' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-03-02T19:48:17.510+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:48:17.547+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 0.607 seconds
[2023-03-02T19:48:31.188+0000] {processor.py:153} INFO - Started process (PID=305) to work on /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:48:31.211+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/convert_txt_in_excel.py for tasks to queue
[2023-03-02T19:48:31.214+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:48:31.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:48:32.473+0000] {logging_mixin.py:137} WARNING - /opt/airflow/dags/convert_txt_in_excel.py:44 DtypeWarning: Columns (7,8,11,13,31,43,44) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-03-02T19:48:32.555+0000] {logging_mixin.py:137} INFO - [2023-03-02T19:48:32.550+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/convert_txt_in_excel.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 44, in <module>
    python_callable=transfrom('/opt/airflow/data')
  File "/opt/airflow/dags/convert_txt_in_excel.py", line 16, in transfrom
    data.to_excel(path + '/DataConvert.xlsx')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2291, in to_excel
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/excel.py", line 835, in write
    writer, engine=engine, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_openpyxl.py", line 48, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
[2023-03-02T19:48:32.582+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/convert_txt_in_excel.py
[2023-03-02T19:48:32.614+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/convert_txt_in_excel.py took 1.434 seconds
