[2023-03-02T21:27:33.866+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T21:27:31.425446+00:00 [queued]>
[2023-03-02T21:27:33.885+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T21:27:31.425446+00:00 [queued]>
[2023-03-02T21:27:33.885+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T21:27:33.885+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-02T21:27:33.885+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T21:27:33.919+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): main> on 2023-03-02 21:27:31.425446+00:00
[2023-03-02T21:27:33.928+0000] {standard_task_runner.py:55} INFO - Started process 1520 to run task
[2023-03-02T21:27:33.933+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'convert_csv_in_excel', 'main', 'manual__2023-03-02T21:27:31.425446+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/convert_csv_in_excel.py', '--cfg-path', '/tmp/tmp2am_c8vx']
[2023-03-02T21:27:33.934+0000] {standard_task_runner.py:83} INFO - Job 129: Subtask main
[2023-03-02T21:27:34.053+0000] {task_command.py:388} INFO - Running <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T21:27:31.425446+00:00 [running]> on host d28bc369eb67
[2023-03-02T21:27:34.216+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=convert_csv_in_excel
AIRFLOW_CTX_TASK_ID=main
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T21:27:31.425446+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-02T21:27:31.425446+00:00
[2023-03-02T21:27:34.221+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/convert_csv_in_excel.py", line 11, in transfrom
    pd.read_csv('../data/operations.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '../data/operations.csv'
[2023-03-02T21:27:34.238+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=convert_csv_in_excel, task_id=main, execution_date=20230302T212731, start_date=20230302T212733, end_date=20230302T212734
[2023-03-02T21:27:34.255+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 129 for task main ([Errno 2] No such file or directory: '../data/operations.csv'; 1520)
[2023-03-02T21:27:34.270+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-02T21:27:34.303+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
