[2023-03-02T21:07:33.122+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T21:07:28.927445+00:00 [queued]>
[2023-03-02T21:07:33.151+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T21:07:28.927445+00:00 [queued]>
[2023-03-02T21:07:33.152+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T21:07:33.152+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-02T21:07:33.152+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T21:07:33.190+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): main> on 2023-03-02 21:07:28.927445+00:00
[2023-03-02T21:07:33.200+0000] {standard_task_runner.py:55} INFO - Started process 370 to run task
[2023-03-02T21:07:33.204+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'convert_csv_in_excel', 'main', 'manual__2023-03-02T21:07:28.927445+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/convert_csv_in_excel.py', '--cfg-path', '/tmp/tmpowbvq8jd']
[2023-03-02T21:07:33.205+0000] {standard_task_runner.py:83} INFO - Job 108: Subtask main
[2023-03-02T21:07:33.303+0000] {task_command.py:388} INFO - Running <TaskInstance: convert_csv_in_excel.main manual__2023-03-02T21:07:28.927445+00:00 [running]> on host d28bc369eb67
[2023-03-02T21:07:33.435+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=convert_csv_in_excel
AIRFLOW_CTX_TASK_ID=main
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T21:07:28.927445+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-02T21:07:28.927445+00:00
[2023-03-02T21:07:33.439+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/convert_csv_in_excel.py", line 11, in transfrom
    ExcelWriter = pd.ExcelWriter()
TypeError: __new__() missing 1 required positional argument: 'path'
[2023-03-02T21:07:33.451+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=convert_csv_in_excel, task_id=main, execution_date=20230302T210728, start_date=20230302T210733, end_date=20230302T210733
[2023-03-02T21:07:33.471+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 108 for task main (__new__() missing 1 required positional argument: 'path'; 370)
[2023-03-02T21:07:33.497+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-02T21:07:33.547+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
